apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # localhost yerine prometheus
    uid: prometheus  # UID ekle
    isDefault: true
    editable: true